/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Item as PrismaItem } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class ItemServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.ItemCountArgs, "select">): Promise<number> {
    return this.prisma.item.count(args);
  }

  async items(args: Prisma.ItemFindManyArgs): Promise<PrismaItem[]> {
    return this.prisma.item.findMany(args);
  }
  async item(args: Prisma.ItemFindUniqueArgs): Promise<PrismaItem | null> {
    return this.prisma.item.findUnique(args);
  }
  async createItem(args: Prisma.ItemCreateArgs): Promise<PrismaItem> {
    return this.prisma.item.create(args);
  }
  async updateItem(args: Prisma.ItemUpdateArgs): Promise<PrismaItem> {
    return this.prisma.item.update(args);
  }
  async deleteItem(args: Prisma.ItemDeleteArgs): Promise<PrismaItem> {
    return this.prisma.item.delete(args);
  }

  async uploadImage<T extends Prisma.ItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaItem> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "image";
    const image = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.item.update({
      where: args.where,

      data: {
        image: image as InputJsonValue,
      },
    });
  }

  async downloadImage<T extends Prisma.ItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemFindUniqueArgs>
  ): Promise<FileDownload> {
    const { image } = await this.prisma.item.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      image as unknown as LocalStorageFile
    );
  }

  async deleteImage<T extends Prisma.ItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemFindUniqueArgs>
  ): Promise<PrismaItem> {
    const { image } = await this.prisma.item.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      image as unknown as LocalStorageFile
    );

    return await this.prisma.item.update({
      where: args.where,

      data: {
        image: Prisma.DbNull,
      },
    });
  }
}
