/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BillingPlanService } from "../billingPlan.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BillingPlanCreateInput } from "./BillingPlanCreateInput";
import { BillingPlan } from "./BillingPlan";
import { BillingPlanFindManyArgs } from "./BillingPlanFindManyArgs";
import { BillingPlanWhereUniqueInput } from "./BillingPlanWhereUniqueInput";
import { BillingPlanUpdateInput } from "./BillingPlanUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BillingPlanControllerBase {
  constructor(
    protected readonly service: BillingPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BillingPlan })
  @nestAccessControl.UseRoles({
    resource: "BillingPlan",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBillingPlan(
    @common.Body() data: BillingPlanCreateInput
  ): Promise<BillingPlan> {
    return await this.service.createBillingPlan({
      data: data,
      select: {
        createdAt: true,
        id: true,
        onHold: true,
        planFees: true,
        planType: true,
        updatedAt: true,
        users: true,
        withdraw: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BillingPlan] })
  @ApiNestedQuery(BillingPlanFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BillingPlan",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async billingPlans(@common.Req() request: Request): Promise<BillingPlan[]> {
    const args = plainToClass(BillingPlanFindManyArgs, request.query);
    return this.service.billingPlans({
      ...args,
      select: {
        createdAt: true,
        id: true,
        onHold: true,
        planFees: true,
        planType: true,
        updatedAt: true,
        users: true,
        withdraw: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BillingPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BillingPlan",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async billingPlan(
    @common.Param() params: BillingPlanWhereUniqueInput
  ): Promise<BillingPlan | null> {
    const result = await this.service.billingPlan({
      where: params,
      select: {
        createdAt: true,
        id: true,
        onHold: true,
        planFees: true,
        planType: true,
        updatedAt: true,
        users: true,
        withdraw: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BillingPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BillingPlan",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBillingPlan(
    @common.Param() params: BillingPlanWhereUniqueInput,
    @common.Body() data: BillingPlanUpdateInput
  ): Promise<BillingPlan | null> {
    try {
      return await this.service.updateBillingPlan({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          onHold: true,
          planFees: true,
          planType: true,
          updatedAt: true,
          users: true,
          withdraw: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BillingPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BillingPlan",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBillingPlan(
    @common.Param() params: BillingPlanWhereUniqueInput
  ): Promise<BillingPlan | null> {
    try {
      return await this.service.deleteBillingPlan({
        where: params,
        select: {
          createdAt: true,
          id: true,
          onHold: true,
          planFees: true,
          planType: true,
          updatedAt: true,
          users: true,
          withdraw: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
