/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { OwnerService } from "../owner.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OwnerCreateInput } from "./OwnerCreateInput";
import { Owner } from "./Owner";
import { OwnerFindManyArgs } from "./OwnerFindManyArgs";
import { OwnerWhereUniqueInput } from "./OwnerWhereUniqueInput";
import { OwnerUpdateInput } from "./OwnerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OwnerControllerBase {
  constructor(
    protected readonly service: OwnerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Owner })
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createOwner(@common.Body() data: OwnerCreateInput): Promise<Owner> {
    return await this.service.createOwner({
      data: data,
      select: {
        address: true,
        cnss: true,
        companyName: true,
        createdAt: true,
        email: true,
        fullName: true,
        ice: true,
        id: true,
        ifField: true,
        password: true,
        phone: true,
        profilePhoto: true,
        rc: true,
        rib: true,
        tp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Owner] })
  @ApiNestedQuery(OwnerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async owners(@common.Req() request: Request): Promise<Owner[]> {
    const args = plainToClass(OwnerFindManyArgs, request.query);
    return this.service.owners({
      ...args,
      select: {
        address: true,
        cnss: true,
        companyName: true,
        createdAt: true,
        email: true,
        fullName: true,
        ice: true,
        id: true,
        ifField: true,
        password: true,
        phone: true,
        profilePhoto: true,
        rc: true,
        rib: true,
        tp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Owner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async owner(
    @common.Param() params: OwnerWhereUniqueInput
  ): Promise<Owner | null> {
    const result = await this.service.owner({
      where: params,
      select: {
        address: true,
        cnss: true,
        companyName: true,
        createdAt: true,
        email: true,
        fullName: true,
        ice: true,
        id: true,
        ifField: true,
        password: true,
        phone: true,
        profilePhoto: true,
        rc: true,
        rib: true,
        tp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Owner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateOwner(
    @common.Param() params: OwnerWhereUniqueInput,
    @common.Body() data: OwnerUpdateInput
  ): Promise<Owner | null> {
    try {
      return await this.service.updateOwner({
        where: params,
        data: data,
        select: {
          address: true,
          cnss: true,
          companyName: true,
          createdAt: true,
          email: true,
          fullName: true,
          ice: true,
          id: true,
          ifField: true,
          password: true,
          phone: true,
          profilePhoto: true,
          rc: true,
          rib: true,
          tp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Owner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOwner(
    @common.Param() params: OwnerWhereUniqueInput
  ): Promise<Owner | null> {
    try {
      return await this.service.deleteOwner({
        where: params,
        select: {
          address: true,
          cnss: true,
          companyName: true,
          createdAt: true,
          email: true,
          fullName: true,
          ice: true,
          id: true,
          ifField: true,
          password: true,
          phone: true,
          profilePhoto: true,
          rc: true,
          rib: true,
          tp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/profilePhoto")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: Owner,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadProfilePhoto(
    @common.Param()
    params: OwnerWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<Owner> {
    return this.service.uploadProfilePhoto(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/profilePhoto")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadProfilePhoto(
    @common.Param()
    params: OwnerWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadProfilePhoto({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/profilePhoto")
  @swagger.ApiOkResponse({
    type: Owner,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteProfilePhoto(
    @common.Param()
    params: OwnerWhereUniqueInput
  ): Promise<Owner> {
    return this.service.deleteProfilePhoto({
      where: params,
    });
  }
}
